### ISSUE TITLE
DateFormat inconsistency with yyyy

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/intl#7] opened 2015-04-30 20:46 UTC
Reported by luna.duclos@palmstonegames.com, Today (7 hours ago)
What steps will reproduce the problem?
1. Create a DateFormat: new DateFormat("yyyyMMdd");
2. format any arbitrary time with it: f.format(new DateTime.now())
3. try and reparse the same date

What is the expected output? What do you see instead?
An exception occurs, instead I'd have expected the dateformat to be able to parse a date that was formatted by it back again. I think this is caused by yyyy being formatted as a single 4 digit year but being parsed differently somehow.

What version of the product are you using?
Dart 1.9.3

On what operating system?
Linux

What browser (if applicable)?
Dartium

Please provide any additional information below.

Today (6 hours ago) Delete comment Project Member #1 gzoechi
DateFormat.parse() expects a string not a DateTime. A String generated from DateTime can be parsed without intl like DateTime.parse(new DateTime.now().toString()). If you want to use DateFormat.parse() you need to pass an appropriate format string.
Today (6 hours ago) Delete comment #2 luna.duclos@palmstonegames.com
I called DateFormat.parse using the same DateFormat generated in step 1, like this:

var format = new DateFormat("yyyyMMdd");
var timeStr = format.format(new DateTime.now());
var reparsed = format.parse(timeStr);

The third line of this will panic

move from SDK issue tracker: https://code.google.com/p/dart/issues/detail?id=23345

**Comment by alan-knight** [comment] 2015-04-30 21:30
This is a duplicate of #3, but it's also infeasible. Will comment there.

**Closed by alan-knight** 2015-04-30 21:30 UTC

**Comment by PSG-Luna** [comment] 2015-04-30 21:36
I'd at least expect an internationalization library to be able to reparse the string it outputted with the exact same format string ? Also, what code would you suggest for parsing hardcoded dates instead of intl ? All pointers in the official docs point at intl as the best candidate to do this

**Comment by alan-knight** [comment] 2015-04-30 22:02
It's very easy to define a format that loses information, so that expectation is not really possible. Where in the official docs is this suggested? We should change it. 

If you want to parse a hardcoded, non-localized format, then I'd suggest something like

https://dartpad.dartlang.org/1be372bab0fa795f93c6

That's much, much less code, and should run a good deal faster.
