### ISSUE TITLE
DateFormat.parse year behaviour is inconsistent with documentation

### ISSUE THREAD

**Issue by mehmetf** [dart-lang/intl#269] opened 2020-03-12 18:29 UTC
The intl DateFormat class states in its documentation that, when parsing, a two digit year will be implied to be within 20 years in the past or 80 years in the future in order to infer the century. However, when actually parsing, it parses the date as being in the 1st century (e.g. 01/22 is parsed as January 0022).

Internal issue: b/151190062

**Comment by jamesderlin** [comment] 2020-05-29 18:50
This is a duplicate of #123.

**Closed** 2021-03-18 08:22 UTC
