### ISSUE TITLE
 Time zone format throws an UnimplementedError

### ISSUE THREAD

**Issue by mdryankov** [dart-lang/intl#229] opened 2019-08-27 09:08 UTC
This is something that is supposed to work according to the documentation:

https://api.flutter.dev/flutter/intl/DateFormat-class.html

Reference: https://github.com/dart-lang/intl/blob/5be03cb1d6613f546702d7ea51bf41e4443d04ca/lib/src/intl/date_format_field.dart#L626

https://github.com/dart-lang/intl/blob/5be03cb1d6613f546702d7ea51bf41e4443d04ca/lib/src/intl/date_format_field.dart#L631

https://github.com/dart-lang/intl/blob/5be03cb1d6613f546702d7ea51bf41e4443d04ca/lib/src/intl/date_format_field.dart#L635

**Comment by ilyaivanov** [comment] 2019-09-19 09:33
From the [docs](https://pub.dev/packages/intl) 

> Known limitations: Time zones are not yet supported. Dart DateTime objects don't have a time zone, so are either local or UTC. Formatting and parsing Durations is not yet implemented.

:(

**Comment by jamesderlin** [comment] 2020-07-29 01:27
This seems like a duplicate of https://github.com/dart-lang/intl/issues/19 or https://github.com/dart-lang/intl/issues/74.

**Comment by mosuem** [comment] 2022-10-27 08:10
Yes, unfortunately it is... Closing in favor of #19 .

**Closed by mosuem** 2022-10-27 08:10 UTC
