### ISSUE TITLE
Cannot reuse DateFormat variable after l10n initialization

### ISSUE THREAD

**Issue by knuesel** [dart-lang/intl#315] opened 2020-10-02 13:22 UTC
It seems that `intl` gets in a corrupted state if a `DateFormat` variable is used before localization is initialized in Flutter. This bug is making Firebase authentication fail on Flutter Web: https://github.com/FirebaseExtended/flutterfire/issues/3374 .

A complete MWE to reproduce this bug is available at https://github.com/knuesel/dateformat_bug : it's a vanilla Flutter app (from `flutter create`) with a few lines of code added to enable localization using the [new Flutter localization process](https://github.com/flutter/flutter/issues/41437).

Here's the essence of the MWE:

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

final format = DateFormat('EEE, d MMM yyyy HH:mm:ss', 'en_US');
final date = 'Fri, 25 Sep 2020 12:39:53 GMT';

void main() {
  print('@ Parsing date in main()...');
  print(format.parse(date)); // Commenting this makes the other parse call work
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      ...
    );
  }
}

class _MyHomePageState extends State<MyHomePage> {
...
  @override
  Widget build(BuildContext context) {
    print('@ Parsing date in widget build...');
    print(format.parse(date));  // This throws an exception

    return ...;
  }
}
```

This code throws an exception:

```
I/flutter (28125): @ Parsing date in main()...
I/flutter (28125): 2020-09-25 12:39:53.000
I/flutter (28125): @ Parsing date in widget build...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following FormatException was thrown building MyHomePage(dirty, state: _MyHomePageState#ff885):
Trying to read EEE from Fri, 25 Sep 2020 12:39:53 GMT at position 0

The relevant error-causing widget was: 
  MyHomePage file:///home/j/temp/dateformat/dateformat_bug/lib/main.dart:40:13
When the exception was thrown, this was the stack: 
#0      _DateFormatField.throwFormatException (package:intl/src/intl/date_format_field.dart:87:5)
#1      _DateFormatPatternField.parseField (package:intl/src/intl/date_format_field.dart:337:7)
#2      _DateFormatPatternField.parse (package:intl/src/intl/date_format_field.dart:250:5)
#3      DateFormat._parse (package:intl/src/intl/date_format.dart:374:13)
#4      DateFormat.parse (package:intl/src/intl/date_format.dart:303:7)
```

As you can see, parsing the **same date string** with the **same DateFormat variable** works in `main()`, but throws when it's run after Flutter localization has been enabled.

The second `parse` call works if we remove the first `parse` in `main`.

Both calls work if we remove the line `localizationsDelegates: AppLocalizations.localizationsDelegates`.

**Comment by alan-knight** [comment] 2020-10-02 13:58
It's probably a bad idea to use intl to parse fixed-format dates. It's slow, bloated, and may fail in interesting circumstances. See #83 for a feature request to provide it better. That being said, this is weird, and doesn't reproduce without Flutter. The parsing of EEE really ought to be pretty robust, and the information from it is ignored. A more detailed stack trace might be useful.

**Comment by knuesel** [comment] 2020-10-02 14:09
@alan-knight I have edited the description to include a bigger stack trace.

**Comment by alan-knight** [comment] 2020-10-02 16:15
Unfortunately, not helpful. However, on a random guess, what is your system locale? The only plausible failure mode for this is that the names of the days of the week are being picked up for a different locale. But that's hard to reconcile with you providing an explicit locale. Or you could try debugging the failing parse and see what weekday names it thinks it has. And if that's true, trying to parse a pattern that uses numerics only should pass, and one that had month names would fail.  https://github.com/dart-lang/intl/blob/master/lib/src/intl/date_format_field.dart#L435 is presumably where it fails.

**Comment by Ehesp** [comment] 2020-10-03 08:18
> It's probably a bad idea to use intl to parse fixed-format dates. It's slow, bloated, and may fail in interesting circumstances.

In this case, the date string comes from a 3rd party library so there isn't much we're able to do until it's reworked.

**Comment by knuesel** [comment] 2020-10-03 10:57
@alan-knight I'm testing this on my phone, in Switzerland, with main language "English (United States)".

I think I have gathered what happens. The exception occurs here: https://github.com/dart-lang/intl/blob/abb648585e8557594a7cb93903bbee9f6a95ff6f/lib/src/intl/date_format_field.dart#L622
Here `symbols` returns null, because the global `_dateTimeSymbols` was reset by `flutter_localization`, see here: https://github.com/flutter/flutter/blob/cbf1e135c4f99cb13148bbf9e062d608ca2cb2f0/packages/flutter_localizations/lib/src/utils/date_localizations.dart#L43

Before this initialization from `flutter_localizations`, `_dateTimeSymbols` was an `UninitializedLocaleData` that supports `en_US`. When `flutter_localizations` makes the first call to `initializeDateFormattingCustom`, `_dateTimeSymbols` is replaced with an empty map. Successive calls to `initializeDateFormattingCustom` fill this map with a whole lot of locales, including `en` but **not** `en_US`. So from then on, my `DateFormat` with locale `en_US` is unusable.

There's still the question, why my second `parse` call works if I remove the first `parse` call in `main`. The reason is that my `format` variable is top-level final, so Dart initializes it when first used. If the first use is after the `flutter_localization` initialization, the `DateFormat` constructor will see there's no symbols for `en_US` so it replaces the locale with `en`.

I suppose the bug is in `flutter_localizations`? Or should `intl` guarantee that `en_US` is usable even if `initializeDateFormattingCustom` is called without setting it?

**Comment by rayk** [comment] 2020-10-07 00:33
Well, this does explain this [issue](https://github.com/FirebaseExtended/flutterfire/issues/3374), for my two cents I would say this a ```Flutter_localization``` issue, probably beyond not calling ```intl``` in the idea fashion. I say this because I would think it would be a reasonable assumption that if the dev explicitly set the locale in let's say the materialApp widget, it would cause ```en_us``` to appear to ```initializeDateFormattingCustom``` map. Which it does not.

Thanks for looking at the @alan-knight and @knuesel  I am still trying to find a workaround, sort of directly manually injecting 'en_us' into the map at some point along the loading process. Any ideas?

Also, any idea who, where we raise this flutter localization issue with? I am assuming it is not an Intl problem.

**Comment by knuesel** [comment] 2020-10-08 15:41
@rayk I filed an issue for `flutter_localizations`: https://github.com/flutter/flutter/issues/67644

**Comment by alan-knight** [comment] 2020-10-08 15:58
An interesting combination. It seems like it's more a Flutter issue. But I'm surprised en_US doesn't just fall back to en. Or to ISO, which is the typical behavior. As a workaround, it might work to explicitly set the locale to just 'en', if they're including that. Or you should (I think) be able to call initializeDateFormattingCustom yourself at more or less any point, and I don't think they should fight.

**Comment by mosuem** [comment] 2022-10-26 13:29
Seems to be fixed in Flutter now.

**Closed by mosuem** 2022-10-26 13:29 UTC
