### ISSUE TITLE
Support for translation modules

### ISSUE THREAD

**Issue by HansMuller** [dart-lang/intl#152] opened 2017-11-16 01:18 UTC
Flutter apps typically segregate `Intl.message` calls in a class, roughly like this:

```
import 'package:intl/intl.dart';
import 'l10n/messages_all.dart';

class MyLocalizations {
  static Future<MyLocalizations> load(String localeName) async {
    await initializeMessages(localeName);
    Intl.defaultLocale = localeName;
    return new MyLocalizations();
  }

  String get title {
    return Intl.message(
      'Hello World',
      name: 'title',
      desc: 'Title for my application',
    );
  }
}
```

In a large app that's been factored into modules, this can be unwieldy because all of the app's Intl.message lookups must be included in a single class. It would be preferable to have one class like `MyLocalizations` for each module.

The `generate_from_arb` app would need an option that generated an initializeMessages() method for a specific module.

An `Intl.message` module parameter would make it possible for the intl package's message lookup logic to distinguish among modules. If the app's message names were globally unique, it would not be necessary to specify this parameter.

**Comment by alan-knight** [comment] 2017-11-30 01:12
I'm assuming that the case here is that each individual component has its own messages and there's no sharing.

I think a reasonable approach for that would be something like the following.

messages_all.dart could include a class Intl which subclasses the regular Intl.
Users would not import intl.dart at all, or if they did, would hide the Intl class.

The version in messages_all.dart would do its own initialization which would return some kind of message lookup object or token. Intl.message calls made through that library would implicitly pass along the token. The biggest negative of this is that the user imports need to change - error detection if you do the wrong thing would be important. The other is that you have a large number of errors if you haven't generated the messages_all.dart file at all. Currently you just have an undefined initializeMessages. With this you'd have every reference to Intl as undefined. However, it's probably not unreasonable to require people to run the initialization step first.

I did a sketch of this, and it doesn't look like it would be too bad to implement, though I haven't done the actual lookup part yet.

**Comment by alan-knight** [comment] 2018-01-02 22:42
I think this is largely a duplicate of #9

**Comment by mosuem** [comment] 2022-11-03 13:53
Closing in favor of #9 .

**Closed by mosuem** 2022-11-03 13:53 UTC
