### ISSUE TITLE
Very strange calculate difference between two dates in UTC

### ISSUE THREAD

**Issue by Bes79** [dart-lang/intl#390] opened 2021-02-02 06:50 UTC
1. Right calculate then not use UTC
```dart
DateTime d1 = DateTime.now().add(Duration(hours: 1));
DateTime d11 = DateFormat('yyyy-MM-dd H:m:s').parse(d1.toString()); // imitation of get DateTime from DB
print(DateTime.now());
print(d11);
print(d11.difference(DateTime.now()).inSeconds);
```
that prints:
```
2021-01-29 19:31:58.854184
2021-01-29 20:31:58.000
3599
```
2. Not right calculate the use UTC
```dart
DateTime d1 = DateTime.now().toUtc().add(Duration(hours: 1));
DateTime d11 = DateFormat('yyyy-MM-dd H:m:s').parse(d1.toString()); // imitation of get DateTime from DB
print(DateTime.now().toUtc());
print(d11);
print(d11.difference(DateTime.now().toUtc()).inSeconds);
```
that prints:
```
2021-01-29 16:40:32.323210Z
2021-01-29 17:40:32.000
-7200
```

**Comment by mosuem** [comment] 2022-10-21 09:16
I may be overlooking something, but isn't this expected behavior? `DateFormat.parse` needs the optional `utc` argument set to true. Please reopen if the issue is not resolved by this.

**Closed by mosuem** 2022-10-21 09:16 UTC
