### ISSUE TITLE
Implement DateFormat time zone formatting

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/intl#74] opened 2015-07-23 16:03 UTC
_From @ajsergeev on July 21, 2015 8:28_

v,z patterns don't work because:

  String formatTimeZoneId(DateTime date) {
    // TODO(alanknight): implement time zone support
    throw new UnimplementedError();
  }

  String formatTimeZone(DateTime date) {
    throw new UnimplementedError();
  }

  String formatTimeZoneRFC(DateTime date) {
    throw new UnimplementedError();
  }

_Copied from original issue: dart-lang/sdk#23879_

**Comment by alan-knight** [comment] 2015-07-23 16:27
Duplicate of #19

We don't expect to implement those until Dart DateTime's have time zone information, and that's not planned. I wouldn't expect it unless/until JavaScript DateTime's have them. Including localized TimeZone names is a lot of data. We should probably just remove those APIs until such time as we actually provide them.

**Comment by pedzed** [comment] 2018-08-15 00:14
@alan-knight Any updates on this? I am using Flutter and I cannot find any information about timezone formatting. I can only find information for localization.

This is a blocker for my app. Perhaps I can temporarily hardcode `+2 hours` (CEST), but that's far from ideal for obvious reasons.

**Comment by pedzed** [comment] 2018-08-15 00:42
Thanks for the pointer to https://pub.dartlang.org/packages/time_machine. I will check it out.

> Dart DateTime's do not have time zone information

I am adding the offset itself when parsing:
```dart
DateTime.parse('2018-01-01 12:00:00 +0200')
```
Can't it be read with [`DateFormat`](https://pub.dartlang.org/documentation/intl/latest/intl/DateFormat-class.html) or something?

I'm sorry. I know that dates are extremely complex, but at the moment this is feels like half work. Dart 2 is released (:tada:), but ~`DateTime` still gives some unimplemented exceptions~ (Never mind, I am probably confusing it with `DateFormat`).

**Comment by pedzed** [comment] 2018-08-18 12:49
I have tried Time Machine, but it is really frustrating that it is lacking (good) documentation.

Either way, I think such an important feature should be supported by the Dart team. What is the reason it is not? Lack of resources or something technical?

> The only other obvious thing is to get time zone information from the operating system directly.

I don't mind trying that. Do you have any pointers for me?

**Comment by duzenko** [comment] 2019-05-24 13:02
> 
> 
> Dart DateTime's do not have time zone information, so no, there isn't much you can do with that. I saw a reference recently to a "Time machine" package which was a port of Joda time to Dart and did include times with time zones. It's possible that would work for you. The only other obvious thing is to get time zone information from the operating system directly.

https://api.dartlang.org/stable/2.3.1/dart-core/DateTime/timeZoneOffset.html

**Comment by alan-knight** [comment] 2019-05-24 17:03
There is a time zone offset, it is effectively global. So DateTime instances can be either in UTC or in the local time. We can get the offset from UTC, but that does not uniquely determine the time zone, and we do not have data included for time zone names. That could be included, but it increases the data size and is not currently planned. We are more likely to delegate this to JS Intl (on web) or to ICU/operating system facilities (on mobile) going forward, rather than adding more subsets of data.

**Comment by duzenko** [comment] 2019-05-25 11:53
You can still format the timezone, regardless if it's local or global.
If it's the DT instance is 'local time' then use its time zone.
If it's 'UTC time', use the GMT zone.
Sorry, I don't see the problem. What data exactly do you need for this?

**Comment by amugofjava** [comment] 2019-06-10 15:57
DateTime will parse standard ISO dates. If you need custom formatting, there is DateFormat (as highlighted above). The documentation suggests that you can use timezone fields when parsing - such as 'z', but in fact the timezone handling methods within date_format_field.dart throws an `UnimplementedError()` exception. This means parsing dates in RFC2822 format is not possible.

**Comment by duzenko** [comment] 2019-06-10 16:02
> `DateTime` will parse standard ISO dates. If you need custom formatting, there is `DateFormat` (as highlighted above). The documentation suggests that you can use timezone fields when parsing - such as 'z', but in fact the timezone handling methods within date_format_field.dart throws an `UnimplementedError()` exception. This means parsing dates in RFC2822 format is not possible.

This issue is about formatting, not parsing.
It's still _possible_ to parse any zone date, it just will need conversion to local/utc zone.

**Comment by jamesderlin** [comment] 2020-07-29 01:27
Is this different from https://github.com/dart-lang/intl/issues/19?

**Comment by duzenko** [comment] 2020-08-11 10:28
> 
> 
> Is this different from #19?

Not unless formatting and parsing are the same thing

**Comment by mosuem** [comment] 2022-10-21 10:56
Closing in favor of #19 .

**Closed by mosuem** 2022-10-21 10:56 UTC
