### ISSUE TITLE
Date parsing fails with no delimiters

### ISSUE THREAD

**Issue by dhenneke** [dart-lang/intl#112] opened 2016-04-02 09:56 UTC
I need to parse a date in the form "201604021140" (yyyyMMddhhmm) but the parsing fails. The problem always occurs when the date format doesn't contain delimiters.

```dart
final format = new DateFormat('yyyyMM');
final d = format.parse('201604');
```

leads to:
```
FormatException: Trying to read MM from 201604 at position 6
#0      _DateFormatField.throwFormatException (package:intl/src/intl/date_format_field.dart:65:5)
#1      _DateFormatPatternField.parseField (package:intl/src/intl/date_format_field.dart:300:7)
#2      _DateFormatPatternField.parse (package:intl/src/intl/date_format_field.dart:224:5)
#3      DateFormat._parse.<anonymous closure> (package:intl/src/intl/date_format.dart:330:36)
#4      List.forEach (dart:core-patch/growable_array.dart:254)
#5      DateFormat._parse (package:intl/src/intl/date_format.dart:330:19)
#6      DateFormat.parse (package:intl/src/intl/date_format.dart:262:7)
#7      main.<main_async_body> (...)
#8      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#11     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Is this format supported? May be related to the following comment: https://github.com/dart-lang/intl/blob/0c284428b4d2b97e944e29e9b5f2c5a5deea39af/lib/src/intl/date_format.dart#L324?

**Comment by alan-knight** [comment] 2016-04-04 14:46
It's not supported, and you probably don't want to use Intl to parse a date like that. If it's a fixed format Intl will both be much slower. It also will be parsed differently in different locales, which I suspect is not what you want. Duplicate of #83

**Closed by alan-knight** 2016-04-04 14:46 UTC

**Comment by ipcjs** [comment] 2021-02-19 10:05
I wrote a [SimpleDateFormat](https://gist.github.com/086e6c07ae0d95d67945355362687bf8) to parse simple pattern like `yyyyMM`.
😵
